### ISSUE TITLE
Histogram bar edges are outside axes

### ISSUE THREAD

**Issue by SebastianM-C** [piever/StatMakie.jl#5]
```julia
using StatsBase
using StatMakie
hist=fit(Histogram, rand(10), closed=:left)
plot(hist)
```
produces
![image](https://user-images.githubusercontent.com/31181429/46030910-23d32100-c100-11e8-8b4c-7ef97a9432e2.png)

**Comment by piever** [comment]
This seems to come from an issue in Makie: I've reposted there at https://github.com/JuliaPlots/Makie.jl/issues/152

**Comment by SebastianM-C** [comment]
Since this is a Makie issue, should this be closed?
